#!/usr/bin/env bash
# Q-EXCISE-LEDGER — one-shot re-runnable QA entry point (read-only).
#
# 1. positive control : harness vs real artifacts              (expect EXIT 0)
# 2. negative control : harness vs un-excised fixture          (expect EXIT != 0)
# 3. ledger diff      : ground truth vs delivered ledger       (expect EXIT != 0 = FALSIFIED)
# 4. required attacks : A1..A8 table with exit codes
#
# Usage: bash vendor/guardtalk/docs/qa/run_q_excise_ledger.sh
set -uo pipefail
ROOT="$(cd "$(dirname "$0")/../../../.." && pwd)"
cd "$ROOT"
QA="vendor/guardtalk/docs/qa"
H="$QA/q_excise_ledger_harness.py"
FIX="$QA/fixtures/un-excised"
EV=".agent-comm/evidence/Q-EXCISE-LEDGER"
mkdir -p "$EV"
SUMMARY="$EV/control_exit_codes.tsv"
: > "$SUMMARY"

echo "=================================================================="
echo "1) POSITIVE CONTROL — harness vs real built artifacts (expect 0)"
echo "   python3 $H --mode artifacts"
python3 "$H" --mode artifacts > "$EV/positive_control.out" 2>&1
p=$?; tail -2 "$EV/positive_control.out" | sed 's/^/   /'
echo "   EXIT=$p"
printf 'positive_control\t%s\n' "$p" >> "$SUMMARY"

echo "=================================================================="
echo "2) NEGATIVE CONTROL — harness vs deliberately UN-EXCISED fixture"
echo "   (fixture regenerated by $QA/make_fixture_un_excised.sh)"
echo "   python3 $H --mode artifacts --fixture $FIX"
python3 "$H" --mode artifacts --fixture "$FIX" > "$EV/negative_control.out" 2>&1
n=$?; grep -E 'MISMATCH|cells=' "$EV/negative_control.out" | sed 's/^/   /'
echo "   EXIT=$n  (MUST be non-zero: a harness that cannot fail is not evidence)"
printf 'negative_control\t%s\n' "$n" >> "$SUMMARY"

echo "=================================================================="
echo "3) LEDGER DIFF — ground truth vs $QA/excision_ledger.json"
echo "   python3 $H --mode ledger"
python3 "$H" --mode ledger > "$EV/ledger_diff.out" 2>&1
l=$?; grep -E 'cells=|RESULT' "$EV/ledger_diff.out" | sed 's/^/   /'
echo "   EXIT=$l  (non-zero == ledger disagrees with primary artifacts)"
printf 'ledger_diff\t%s\n' "$l" >> "$SUMMARY"

echo "=================================================================="
echo "4) REQUIRED ATTACKS A1..A8"
bash "$QA/q_excise_ledger_attacks.sh" > "$EV/attacks_console.out" 2>&1
a=$?; sed 's/^/   /' "$EV/attack_exit_codes.tsv"
echo "   attacks_script EXIT=$a"
printf 'attacks\t%s\n' "$a" >> "$SUMMARY"

echo "=================================================================="
echo "SUMMARY ($SUMMARY)"
column -t -s$'\t' "$SUMMARY"
