# vendor/guardtalk/feature-excised/init-rc-excised.mk
#
# T-EXCISE-INIT-RC-REWRITE (2026-09-26) — durable build-time init-rc REWRITE filter.
#
# DECISION (Architect, 2026-09-26, resolving T-EXCISE-ABOX-THERMAL-UNSHIPPED):
#   option (a) hand-editing the factory prebuilts is REJECTED;
#   option (b) a durable BUILD-TIME filter is ADOPTED.
#
# WHY NOT JUST EDIT THE RC FILES: they live under
#   vendor/google_devices/<dev>/proprietary/vendor/etc/init/hw/init.<soc>.rc
# and are (i) read-only, (ii) regen-managed — T-EXCISE-REGEN-GUARD records
# skel<->generated byte-identity 6/6, so an `adevtool` regeneration WILL
# overwrite any hand-edit — and (iii) SHARED (each carries many unrelated
# services, so a whole-file PRODUCT_COPY_FILES drop cannot be used). Excision
# must therefore live in a hand-maintained mk overlay, exactly like the sibling
# filters radio-excised/vintf-excised.mk and feature-excised/fp-excised.mk.
#
# WHAT THIS FILTER REMOVES (spec = the prepared, never-applied
# .agent-comm/evidence/T-EXCISE-ABOX-THERMAL-UNSHIPPED/proposed_source_drop.patch,
# 14 rc files / 220 diff lines):
#   * on the 13 program products: the exact block
#         service abox /vendor/bin/main_abox 17c50000.abox
#             class late_start / user audioserver / group audioserver
#             seclabel u:r:abox:s0
#     (its `seclabel` rides inside the block), because main_abox ships in NO
#     image (confirmed 13/13 via debugfs on the shipped stamps); and
#   * on `rango`: the exact block
#         service init_thermal_config /vendor/bin/rango_init_thermal_config
#             class main / user root / group root system / disabled / oneshot
#     plus its 3 debug-gated `on ... start init_thermal_config` actions, because
#     /vendor/bin/rango_init_thermal_config ships in no image.
#
# MECHANISM — no prebuilt is ever written:
#   For the building device only, the matching PRODUCT_COPY_FILES pair
#   `vendor/google_devices/<dev>/proprietary/vendor/etc/init/hw/<rc> : <dest>`
#   is REPLACED by a generated pair `<OUT_DIR>/guardtalk/init-rc-excised/<dev>/<rc> : <dest>`.
#   The generated file is produced at product-config time by
#   vendor/guardtalk/feature-excised/init-rc-rewrite.py, which reads the current
#   prebuilt and removes ONLY the exact service block (+ its `start` actions).
#   Because the rewrite is derived from the live prebuilt on every parse, an
#   adevtool regen cannot resurrect the entry and cannot overwrite the excision
#   (nothing is stored under proprietary/**). The generated file is a normal
#   copy-file source, so the standard build path (`check-product-copy-files` ->
#   `copy-init-script-file-checked` / `copy-one-file`) treats it like any other
#   prebuilt — including the host init-script verifier.
#
# OVER-MATCH SAFETY:
#   * the service is matched by EXACT name AND EXACT binary, so a same-named
#     service bound to a different binary is never touched (e.g. comet's shipped
#     `service init_thermal_config /vendor/bin/init_thermal_config` in
#     init.comet.rc — comet is not even in the thermal table);
#   * the device->rc table is explicit (13 abox files + 1 rango thermal file);
#   * the rewrite is idempotent (an already-excised source is a NOOP copy-through);
#   * QIRC-1: a `start <svc>` inside a SHARED `on` block has ONLY that line cut —
#     the block's unrelated commands and its trigger survive (whole dedicated
#     blocks are still removed in full, so the 14 real outputs are byte-identical);
#   * QIRC-2: the fail-closed check keys on the generator's EXIT STATUS (sentinel
#     `GT_INIT_RC_REWRITE_RC=0`), not on the "ERROR" substring;
#   * QIRC-3: the generated rc is wired to EVERY destination of a source pair, so
#     a multi-destination source is never silently reduced to its first;
#   * a partial/ambiguous match or a surviving reference to the removed service
#     fails the build loudly (Law 3) instead of silently no-opping.
#
# HONESTY POSTURE (Law 7): this is a BUILD-SOURCE claim. It changes what a
# FUTURE build copies into vendor.img; it does NOT change any shipped stamp.
# `hold_services_total` stays 14 until a re-stamp — removing the
# `.agent-comm/tools/gt-init-excisions.yaml` entries against the CURRENT stamps
# turns G6 RED (`orphan=2`, `missing_labels=1`). RESTAMP_PERFORMED=false,
# BOOT_VERIFIED=false.
#
# Reversible (Law 11): delete this block + the one `include` line in
# radio-excised/product-config-late.mk. Idempotent (Law 8).

GT_INIT_RC_REWRITER := vendor/guardtalk/feature-excised/init-rc-rewrite.py
GT_INIT_RC_GEN_ROOT := $(if $(OUT_DIR),$(OUT_DIR),out)/guardtalk/init-rc-excised
GT_INIT_RC_DEVICE := $(strip $(if $(PRODUCT_DEVICE),$(PRODUCT_DEVICE),$(TARGET_DEVICE)))

# device:rc table — the file that declares the unshipped `abox` daemon on each
# of the 13 program products.
GT_INIT_RC_ABOX_TABLE := \
    akita:init.zuma.rc \
    husky:init.zuma.rc \
    shiba:init.zuma.rc \
    blazer:init.laguna.rc \
    frankel:init.laguna.rc \
    mustang:init.laguna.rc \
    rango:init.laguna.rc \
    caiman:init.zumapro.board.rc \
    comet:init.zumapro.board.rc \
    komodo:init.zumapro.board.rc \
    stallion:init.zumapro.board.rc \
    tegu:init.zumapro.board.rc \
    tokay:init.zumapro.board.rc

# device:rc table — rango's unshipped thermal helper (the ONLY thermal target;
# the binary path is checked exactly, so comet's shipped init_thermal_config is
# never matched).
GT_INIT_RC_THERMAL_TABLE := rango:init.rango.rc

# Only the building device's entry can ever be active (PRODUCT_COPY_FILES only
# holds the current product's pairs), so each filter matches at most one file.
_gt_init_rc_abox_entry := $(filter $(GT_INIT_RC_DEVICE):%,$(GT_INIT_RC_ABOX_TABLE))
_gt_init_rc_thermal_entry := $(filter $(GT_INIT_RC_DEVICE):%,$(GT_INIT_RC_THERMAL_TABLE))

# ---------------------------------------------------------------------------
# abox: replace the copy pair with a generated filtered copy.
# ---------------------------------------------------------------------------
ifneq ($(_gt_init_rc_abox_entry),)
$(eval _gt_irc_dev := $(word 1,$(subst :, ,$(_gt_init_rc_abox_entry))))
$(eval _gt_irc_rc := $(word 2,$(subst :, ,$(_gt_init_rc_abox_entry))))
$(eval _gt_irc_src := vendor/google_devices/$(_gt_irc_dev)/proprietary/vendor/etc/init/hw/$(_gt_irc_rc))
$(eval _gt_irc_pairs := $(filter $(_gt_irc_src):%,$(PRODUCT_COPY_FILES)))
ifneq ($(_gt_irc_pairs),)
_gt_irc_dsts := $(foreach p,$(_gt_irc_pairs),$(word 2,$(subst :, ,$(p))))
_gt_irc_gen := $(GT_INIT_RC_GEN_ROOT)/$(_gt_irc_dev)/$(_gt_irc_rc)
# QIRC-2: key the fail-closed check on the generator's real EXIT STATUS, not on
# the "ERROR" substring (which could false-positive on an unrelated token or
# false-negative on a silent crash).  The sentinel is appended by the same shell
# so it always reports the generator's status; a missing sentinel is an error.
# NOTE: plain `:=` (NOT `$(eval ...)`) — quoting/comment chars in the captured
# stderr must not be re-parsed as makefile syntax, or a `#` would truncate the
# report (and the sentinel) before it is read.
_gt_irc_report := $(shell mkdir -p $(GT_INIT_RC_GEN_ROOT)/$(_gt_irc_dev) && python3 $(GT_INIT_RC_REWRITER) --src $(_gt_irc_src) --dst $(_gt_irc_gen) --service abox --binary /vendor/bin/main_abox 2>&1; printf 'GT_INIT_RC_REWRITE_RC=%d\n' $$?)
_gt_irc_rc_exit := $(lastword $(filter GT_INIT_RC_REWRITE_RC=%,$(_gt_irc_report)))
$(if $(filter GT_INIT_RC_REWRITE_RC=0,$(_gt_irc_rc_exit)),,$(error T-EXCISE-INIT-RC-REWRITE: generator failed ($(if $(_gt_irc_rc_exit),$(_gt_irc_rc_exit),missing-exit-status)) src=$(_gt_irc_src): $(_gt_irc_report)))
$(if $(wildcard $(_gt_irc_gen)),,$(error T-EXCISE-INIT-RC-REWRITE: generator produced no file: $(_gt_irc_gen)))
# QIRC-3: map the generated rc to EVERY destination of the source (not just the
# first), so a multi-destination source is never silently reduced.
$(eval PRODUCT_COPY_FILES := $(filter-out $(_gt_irc_pairs),$(PRODUCT_COPY_FILES)))
$(eval PRODUCT_COPY_FILES += $(foreach d,$(_gt_irc_dsts),$(_gt_irc_gen):$(d)))
endif
endif

# ---------------------------------------------------------------------------
# rango thermal: replace the copy pair with a generated filtered copy.
# ---------------------------------------------------------------------------
ifneq ($(_gt_init_rc_thermal_entry),)
$(eval _gt_irt_dev := $(word 1,$(subst :, ,$(_gt_init_rc_thermal_entry))))
$(eval _gt_irt_rc := $(word 2,$(subst :, ,$(_gt_init_rc_thermal_entry))))
$(eval _gt_irt_src := vendor/google_devices/$(_gt_irt_dev)/proprietary/vendor/etc/init/hw/$(_gt_irt_rc))
$(eval _gt_irt_pairs := $(filter $(_gt_irt_src):%,$(PRODUCT_COPY_FILES)))
ifneq ($(_gt_irt_pairs),)
_gt_irt_dsts := $(foreach p,$(_gt_irt_pairs),$(word 2,$(subst :, ,$(p))))
_gt_irt_gen := $(GT_INIT_RC_GEN_ROOT)/$(_gt_irt_dev)/$(_gt_irt_rc)
# QIRC-2: exit-status key (see the abox block above; plain `:=`, not `$(eval)`).
_gt_irt_report := $(shell mkdir -p $(GT_INIT_RC_GEN_ROOT)/$(_gt_irt_dev) && python3 $(GT_INIT_RC_REWRITER) --src $(_gt_irt_src) --dst $(_gt_irt_gen) --service init_thermal_config --binary /vendor/bin/rango_init_thermal_config 2>&1; printf 'GT_INIT_RC_REWRITE_RC=%d\n' $$?)
_gt_irt_rc_exit := $(lastword $(filter GT_INIT_RC_REWRITE_RC=%,$(_gt_irt_report)))
$(if $(filter GT_INIT_RC_REWRITE_RC=0,$(_gt_irt_rc_exit)),,$(error T-EXCISE-INIT-RC-REWRITE: generator failed ($(if $(_gt_irt_rc_exit),$(_gt_irt_rc_exit),missing-exit-status)) src=$(_gt_irt_src): $(_gt_irt_report)))
$(if $(wildcard $(_gt_irt_gen)),,$(error T-EXCISE-INIT-RC-REWRITE: generator produced no file: $(_gt_irt_gen)))
# QIRC-3: map the generated rc to EVERY destination of the source.
$(eval PRODUCT_COPY_FILES := $(filter-out $(_gt_irt_pairs),$(PRODUCT_COPY_FILES)))
$(eval PRODUCT_COPY_FILES += $(foreach d,$(_gt_irt_dsts),$(_gt_irt_gen):$(d)))
endif
endif

_gt_init_rc_abox_entry :=
_gt_init_rc_thermal_entry :=
